### ISSUE TITLE
Outdated Documentation for Map.Grow

### ISSUE THREAD

**Issue by StandoffVenus** [alphadose/haxmap#12]
The `map.Grow` method's comment states:
> Grow resizes the hashmap to a new size, gets rounded up to next power of 2
> To double the size of the hashmap use newSize 0
> This function returns immediately, the resize operation is done in a goroutine
> No resizing is done in case of another resize operation already being in progress
> Growth and map bucket policy is inspired from https://github.com/cornelk/hashmap

But commit [d071dd5f749f86017a32bc126ea40eaade5f3dfc](https://github.com/alphadose/haxmap/commit/d071dd5f749f86017a32bc126ea40eaade5f3dfc) changed `map.Grow` to be sync, making this part of the comment inaccurate:
> This function returns immediately, the resize operation is done in a goroutine

**Comment by alphadose** [comment]
@StandoffVenus fixed with https://github.com/alphadose/haxmap/commit/93384692831914eb6ea316fcfd7caf0898a4c5b8
