### ISSUE TITLE
Missed func LoadOrStore 

### ISSUE THREAD

**Issue by CMGS** [alphadose/haxmap#15]
Hi it's a great project but miss [LoadOrStore](https://pkg.go.dev/sync#Map.LoadOrStore) func.

Can just Get first then set?

**Comment by alphadose** [comment]
yes this is really useful, I will implement and test this and put it out in the next release

**Comment by alphadose** [comment]
@CMGS feature added in the new release https://github.com/alphadose/haxmap/releases/tag/v1.1.0
