### ISSUE TITLE
CompareAndStore would be nice

### ISSUE THREAD

**Issue by lkarlslund** [alphadose/haxmap#18]
For concurrent programs a compare and swap value would be really neat, as you might have a race if multiple threads are doing:

```
value, _ := map.Load(key)
value.Modify()
map.Store(key, value)
```

The pattern could be changed to

```
for {
  oldvalue, _ := map.Load(key)
  newvalue := oldvalue
  newvalue.Modify()
  success := map.CompareAndStore(key, oldvalue, newvalue)
  if success {
    break
  }
}
```

**Comment by alphadose** [comment]
Yes this is useful, will add it in the next release 👍

**Comment by alphadose** [comment]
will the API look something like this ? `map.CompareAndSwap(key, oldValue, newValue) bool` ?

**Comment by lkarlslund** [comment]
Also variants like LoadOrCalculate would be pretty awesome (same behaviour as LoadOrStore, but you give it a function that returns the value to store, for complex or costly generators of values). The xsync module (https://github.com/puzpuzpuz/xsync) has those, if you need some inspiration.
But really great job on this module so far!

**Comment by alphadose** [comment]
@lkarlslund 

> Also variants like LoadOrCalculate would be pretty awesome (same behaviour as LoadOrStore, but you give it a function that returns the value to store, for complex or costly generators of values).

This is similar to https://github.com/alphadose/haxmap/issues/16

**Comment by bagualing** [comment]
Could you also consider adding two atomic APIs: Swap and CompareAndSwap?
```
func (m *Map[K, V]) Swap(key K, newValue V) (oldValue V){}
func (m *Map[K, V]) CompareAndSwap(Key K, oldValue, newValue V) (swapped bool){}
```
I have encountered this requirement in my usage scenario, so, I think it's mybee useful too.

**Comment by bagualing** [comment]
Could you also consider adding two atomic APIs: Swap and CompareAndSwap?
```
func (m *Map[K, V]) Swap(key K, newValue V) (oldValue V){}
func (m *Map[K, V]) CompareAndSwap(Key K, oldValue, newValue V) (swapped bool){}
```
I have encountered this requirement in my usage scenario, so, I think it's mybee useful too.

**Comment by alphadose** [comment]
@bagualing `CompareAndSwap` is the same as `CompareAndStore` described by @lkarlslund above
I have taken note of `Swap` API and shall add it

**Comment by alphadose** [comment]
@lkarlslund @bagualing both `CompareAndSwap` and `Swap` have been added with https://github.com/alphadose/haxmap/commit/5f15ec73a34ab8b8e6494894dcf25bc9a095cbc4
