### ISSUE TITLE
Cannot set maps above a certain size

### ISSUE THREAD

**Issue by nightwolfz** [alphadose/haxmap#2]
go 1.19

```go
func TestMakeHaxmap(t *testing.T) {
	for f := 1; f < 1000000; f *= 5 {
		m := haxmap.New[int, string]()
		t.Logf("creating %d", f)

		for i := 0; i < f; i++ {
			m.Set(i, fmt.Sprintf("a%d", i))
		}

		t.Logf("size: %d", m.Size())
	}
}
```

Randomly hangs forever...

**Comment by alphadose** [comment]
Hi @nightwolfz , can you try it with an initial size such as `m := haxmap.New[int, string](1 << 12)` ?

**Comment by alphadose** [comment]
@nightwolfz yes rapid map growth via `Set()` creates a lot of `grow()` goroutines which causes choking and as you said using `runtime.Gosched()` frees up the CPU hence more time for the growth.

One of haxmap's future goals is a better growth policy which wont choke and hence there is lots more room for improvement

> If this is by design, it might be worth mentioning in the README.
Yes, I will mention it

Also the current workaround for this behaviour would be initializing the map with a good size which will cause lesser grow operations and wont choke

**Comment by alphadose** [comment]
Yes, this sounds plausible, if possible can you checkout a branch with these changes ? It would be much easier for both of us to test that way.

**Comment by alphadose** [comment]
@nightwolfz I have updated the main branch with this https://github.com/alphadose/haxmap/commit/d071dd5f749f86017a32bc126ea40eaade5f3dfc

With this commit growth happens synchronously and my benchmarks and tests are passing as well

can you run your tests once again and tell me the results ?
