### ISSUE TITLE
UUID for Key?

### ISSUE THREAD

**Issue by jaekook-neonesia** [alphadose/haxmap#27]
Hi, thank you for your excellent map. How can I use google/UUID for the key? or can you add this feature to the map?

**Comment by alphadose** [comment]
@jaekook-neonesia the underlying type of UUID is `[16]byte` which doesn't have the comparable trait in golang (==, != etc)

Hence, it is not possible to implement UUID in this map implementation.

To add UUID support, a copy of this map has to be made specifically for using UUID as a key, it will no longer be generic in nature
