### ISSUE TITLE
Plan for new release

### ISSUE THREAD

**Issue by gasuketsu** [alphadose/haxmap#40]
Thank you for excellent map library.

It looks that several fixes and new APIs are added after v1.2.0.
Do you have any plan to release them ?

**Comment by alphadose** [comment]
@gasuketsu yes you are right, I had forgotten about it. Apologies.
Here is the latest release https://github.com/alphadose/haxmap/releases/tag/v1.3.0

Thank you once again @semihbkgr for fixing critical bugs, json encoding and adding the much-needed `GetAndDel` function 🙏
