### ISSUE TITLE
New() initializer panics if the given size is uintptr(0)

### ISSUE THREAD

**Issue by chiho20** [alphadose/haxmap#42]
I wanted to initialize a haxmap B with the same size as haxmap A with the following code:
```
B := haxmap.New[string, struct{}](A.Len())
```
which worked for most cases except when A.Len() is 0. When A has 0 key-values, the initializer would panic. 

Would be awesome if this is handled 🙏

**Comment by alphadose** [comment]
@chiho20 got it, will make the changes and release new minor version soon 👍

**Comment by semihbkgr** [comment]
I've created a PR that references this issue: #44
