### ISSUE TITLE
When to use this package

### ISSUE THREAD

**Issue by vtolstov** [alphadose/haxmap#9]
In which cases using this package really needed vs standard go map with mutex?
For example if I have 10 entries?

**Comment by alphadose** [comment]
for small datasets there wouldn't be any noticeable difference between haxmap and the default go map.

the difference would start to show with an increase in dataset size and more number of goroutines reading/writing concurrently in which case mutex locking/unlocking would be much slower as compared to haxmap which uses lock-free linked list internally

**Comment by vtolstov** [comment]
Thank you
